//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheets.Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelsContext : DbContext
    {
        public ModelsContext()
            : base("name=ModelsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<TemplateType> TemplateTypes { get; set; }
        public virtual DbSet<TemplateField> TemplateFields { get; set; }
        public virtual DbSet<Setting> Settings1 { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<DatabaseConnection> DatabaseConnections { get; set; }
        public virtual DbSet<DatabaseQuery> DatabaseQueries { get; set; }
        public virtual DbSet<RecipientAttribute> RecipientAttributes { get; set; }
    }
}
