//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheets.HostedApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseConnection
    {
        public DatabaseConnection()
        {
            this.DatabaseQueries = new HashSet<DatabaseQuery>();
        }
    
        public int Id { get; set; }
        public string ProviderType { get; set; }
        public string Name { get; set; }
        public string ConnectionString { get; set; }
    
        public virtual ICollection<DatabaseQuery> DatabaseQueries { get; set; }
    }
}
