//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheets.HostedApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceRecipient : Recipient
    {
        public bool IsSgt { get; set; }
        public string ControlCode { get; set; }
    }
}
