//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheets.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateType
    {
        public TemplateType()
        {
            this.Recipients = new HashSet<Recipient>();
            this.TemplateFields = new HashSet<TemplateField>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Format { get; set; }
    
        public virtual ICollection<Recipient> Recipients { get; set; }
        public virtual ICollection<TemplateField> TemplateFields { get; set; }
    }
}
