//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheets.HostedApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Recipient
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int TemplateTypeId { get; set; }
    
        public virtual TemplateType TemplateType { get; set; }
    }
}
